services:
  web:
    build: ./web
    image: tp-compose-web
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - api
    networks:
      - frontend

  api:
    build: ./api
    image: tp-compose-api
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - db
    ports:
      - "8088:3000"
    networks:
      - frontend
      - backend

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db_data:

networks:
  frontend:
  backend: